# AWS DISCLAMER
# Provided to Customer on 12 March 2020
# ---

# The following files are provided by AWS Professional Services describe the process to create an read-only breakglass role for security within your AWS Automated Landing Zone. These are non-production ready and are to be used for testing purposes.

# These files is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
# OR CONDITIONS OF ANY KIND, either express or implied. See the License
# for the specific language governing permissions and limitations under the License.

# (c) 2019 Amazon Web Services, Inc. or its affiliates. All Rights Reserved.
# This AWS Content is provided subject to the terms of the AWS Customer Agreement available at
# http://aws.amazon.com/agreement or other written agreement between Customer and Amazon Web Services, Inc.​


apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: de-iot-sdbx3-fargate
  region: us-east-1
  #version: "1.14"

vpc:
  #clusterEndpoints:
    #publicAccess:  true
    #privateAccess: true
  id: "vpc-0499ce6bc647bff24"  
  cidr: "172.31.0.0/16"
  subnets:
    # must provide 'private' and/or 'public' subnets by availibility zone as shown
    private:
      us-east-1a:
        id: "subnet-017e96618658d1383"
        cidr: "172.31.100.0/24" 
      us-east-1b:
        id: "subnet-0ebdef638fbfd2c0b"
        cidr: "172.31.101.0/24"  
      us-east-1c:
        id: "subnet-0dcc08ba81ccd6b65"
        cidr: "172.31.102.0/24"

#To use custom IAM role for the EKS cluster uncomment the section below and replace the ARN for the IAM role.
iam:
  serviceRoleARN: "arn:aws:iam::057929149431:role/eksFargateServiceRole"

fargateProfiles:

  - name: alb-ingress-controller
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: kube-system
      
  - name: coredns
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: kube-system
      
  - name: metrics-server
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: kube-system #metrics
      
  - name: de-iot-sdbx-fargate
    selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      - namespace: default
      
  #- name: fp-dev
    #selectors:
      # All workloads in the "dev" Kubernetes namespace matching the following
      # label selectors will be scheduled onto Fargate:
      #- namespace: dev
        #You can optionally specify Kubernetes labels to match for the selector. The selector only matches pods that have all of the labels that are specified in the selector.
        #labels:
          #env: dev
          #check: passed
    #The IDs of subnets to launch pods into that use this profile. At this time, pods running on Fargate are not assigned public IP addresses, so only private subnets (with no direct route to an Internet Gateway) are accepted for this parameter.      
    #subnets:
    #- subnet-017e96618658d1383
    #- subnet-0ebdef638fbfd2c0b
    #- subnet-0dcc08ba81ccd6b65
          
cloudWatch:
  clusterLogging:
    enableTypes: ["*"]